spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
  message :
    basename : validation
    encoding : UTF-8
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace